
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.facebook.fbreact.specs;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeBiometricLoginSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "BiometricLogin";

  public NativeBiometricLoginSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void BiometricIsAvailable(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void BasicBiometricAuth(String title, String desc, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void LoginBiometricAuth(String title, String desc, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void SetUser(String username, String password, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void UpdateUser(String username, String password, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void GetUser(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void DeleteUser(Promise promise);
}
